services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3005:3000"
    volumes:
      - ./frontend/:/usr/app/
      - dependencies:/usr/app/node_modules
    restart: always
volumes:
  dependencies: