version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3005:3005
    volumes:
      - ./frontend/:/usr/app/
      - dependencies:/usr/app/node_modules
    restart: always
volumes:
  dependencies: